// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/app-grid-button.tsx
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// The 9-grid launcher button. Rendered by PortalProvider ONLY when hosted, so
// a standalone app shows nothing. It's just the trigger — clicking it asks the
// portal to draw its own launcher overlay (which can break out of the iframe);
// the app never needs to know the full catalog to render this.

import AppsIcon from "@mui/icons-material/Apps";
import { Fab, Tooltip } from "@mui/material";

export interface AppGridButtonProps {
  onClick: () => void;
}

export function AppGridButton({ onClick }: AppGridButtonProps): React.ReactNode {
  return (
    <Tooltip title="Apps" placement="left">
      <Fab
        size="small"
        color="default"
        aria-label="open app launcher"
        onClick={onClick}
        sx={{
          position: "fixed",
          top: 12,
          right: 12,
          // Above app chrome but below modal dialogs (MUI modal = 1300).
          zIndex: 1250,
          opacity: 0.85,
          "&:hover": { opacity: 1 },
        }}
      >
        <AppsIcon />
      </Fab>
    </Tooltip>
  );
}
