// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/app-grid-button.tsx
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// The launcher TRIGGER an app places in its own header (top-left, by
// convention) so it sits natively in the app's chrome — not a floating overlay.
//
// It self-hides when the app isn't hosted, so a standalone app shows nothing:
// drop it into your toolbar unconditionally and it only appears inside the
// portal. Clicking it merely asks the portal to raise the launcher — the popup
// UI and all navigation are the portal's job; the app only triggers it.

import AppsIcon from "@mui/icons-material/Apps";
import { IconButton, Tooltip } from "@mui/material";

import { usePortal } from "./provider";

export interface PortalLauncherButtonProps {
  /** Pass edge="start" when it's the first item in a toolbar (tighter inset). */
  edge?: "start" | "end" | false;
  /** Override the icon button size to match the host app's toolbar. */
  size?: "small" | "medium" | "large";
}

export function PortalLauncherButton({
  edge = false,
  size = "medium",
}: PortalLauncherButtonProps): React.ReactNode {
  const { hosted, openLauncher } = usePortal();
  if (!hosted) return null;
  return (
    <Tooltip title="Apps">
      <IconButton
        color="inherit"
        edge={edge}
        size={size}
        aria-label="open app launcher"
        onClick={openLauncher}
      >
        <AppsIcon fontSize={size === "small" ? "small" : "medium"} />
      </IconButton>
    </Tooltip>
  );
}
