// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/protocol.ts
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// The wire contract between an app (inside an iframe) and the atlantis portal
// (the parent window). Both sides import this file: the app via the vendored
// copy under web/src/_shell/, the portal directly from the canonical source.
//
// Every message is tagged with `channel` + `v` so it never collides with other
// postMessage traffic on the window (Vite HMR, MUI, third-party widgets, ...).

export const CHANNEL = "atlantis-shell" as const;
export const PROTOCOL_VERSION = 1 as const;

/** Theme mode the portal pushes down so every app flips light/dark together. */
export type ThemeMode = "light" | "dark";

/** Foreground/background — the portal tells a kept-alive iframe to yield CPU. */
export type Visibility = "foreground" | "background";

/** One app as the portal knows it (derived from project-defs `webui` blocks). */
export interface AppMeta {
  readonly id: string;
  readonly displayName: string;
  readonly icon: string;
  readonly color: string;
}

/** A cross-app bus event. `from` is set by the portal on delivery. */
export interface BusEvent {
  readonly type: string;
  readonly payload?: unknown;
  readonly from?: string;
}

interface Envelope {
  readonly channel: typeof CHANNEL;
  readonly v: typeof PROTOCOL_VERSION;
}

// ── App → Portal ───────────────────────────────────────────────────────────

/** Sent on mount to probe for the portal and start the handshake. */
export interface HelloMsg extends Envelope {
  readonly kind: "hello";
  readonly appId: string;
  readonly appVersion?: string;
}

/** "Show me the launcher" — fired by the 9-grid button. */
export interface OpenLauncherMsg extends Envelope {
  readonly kind: "open-launcher";
}

/** Ask the portal to switch to / open another app, optionally deep-linked. */
export interface NavigateMsg extends Envelope {
  readonly kind: "navigate";
  readonly appId: string;
  readonly path?: string;
  readonly payload?: unknown;
}

/** Publish a bus event for other apps. */
export interface EmitMsg extends Envelope {
  readonly kind: "emit";
  readonly event: BusEvent;
}

export type AppMessage = HelloMsg | OpenLauncherMsg | NavigateMsg | EmitMsg;

// ── Portal → App ─────────────────────────────────────────────────────────────

/** Handshake reply: confirms hosting and hands over context. */
export interface WelcomeMsg extends Envelope {
  readonly kind: "welcome";
  readonly appId: string;
  readonly portalVersion: string;
  readonly mode: ThemeMode;
  readonly catalog: readonly AppMeta[];
}

export interface ThemeMsg extends Envelope {
  readonly kind: "theme";
  readonly mode: ThemeMode;
}

export interface VisibilityMsg extends Envelope {
  readonly kind: "visibility";
  readonly state: Visibility;
}

/** A deep-link payload delivered when the portal opens/focuses this app. */
export interface OpenWithMsg extends Envelope {
  readonly kind: "open-with";
  readonly path?: string;
  readonly payload?: unknown;
}

/** Bus event delivered to a subscriber. */
export interface EventMsg extends Envelope {
  readonly kind: "event";
  readonly event: BusEvent;
}

export type PortalMessage =
  | WelcomeMsg
  | ThemeMsg
  | VisibilityMsg
  | OpenWithMsg
  | EventMsg;

// ── Helpers ──────────────────────────────────────────────────────────────────

export const envelope = { channel: CHANNEL, v: PROTOCOL_VERSION } as const;

/** Narrow an untrusted `MessageEvent.data` to a typed shell message. */
export function parse<T extends Envelope & { kind: string }>(
  data: unknown,
): T | null {
  if (typeof data !== "object" || data === null) return null;
  // Bracket access: callers may compile with noPropertyAccessFromIndexSignature.
  const m = data as Record<string, unknown>;
  if (m["channel"] !== CHANNEL || m["v"] !== PROTOCOL_VERSION) return null;
  if (typeof m["kind"] !== "string") return null;
  return m as unknown as T;
}
