// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/provider.tsx
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// PortalProvider — the app-side half of the atlantis contract.
//
// On mount it posts `hello` to the parent window and waits for `welcome`. If
// it arrives within HANDSHAKE_TIMEOUT_MS from a trusted origin, the app is
// "hosted": the 9-grid launcher button appears, theme mode follows the portal,
// and the cross-app bus is live. No reply → standalone, and nothing renders.

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";

import {
  type AppMeta,
  type BusEvent,
  envelope,
  parse,
  type PortalMessage,
  type ThemeMode,
  type Visibility,
} from "./protocol";

const HANDSHAKE_TIMEOUT_MS = 1000;

export interface NavigateOptions {
  readonly path?: string;
  readonly payload?: unknown;
}

export interface PortalApi {
  /** True once the atlantis portal has acknowledged the handshake. */
  readonly hosted: boolean;
  /** Theme mode the portal dictates (standalone defaults to "light"). */
  readonly mode: ThemeMode;
  /** Every app the portal can launch (empty when standalone). */
  readonly catalog: readonly AppMeta[];
  /** Foreground/background, for kept-alive iframes to yield CPU. */
  readonly visibility: Visibility;
  /** Ask the portal to reveal its launcher overlay. */
  openLauncher(): void;
  /** Switch to / open another app, optionally deep-linked. */
  navigateTo(appId: string, opts?: NavigateOptions): void;
  /** Publish a bus event for other apps. */
  emit(type: string, payload?: unknown): void;
  /** Subscribe to a bus event type. Returns an unsubscribe fn. */
  on(type: string, handler: (event: BusEvent) => void): () => void;
  /** Subscribe to deep-link opens targeting this app. Returns unsubscribe. */
  onOpenWith(handler: (path: string | undefined, payload: unknown) => void): () => void;
}

const standalone: PortalApi = {
  hosted: false,
  mode: "light",
  catalog: [],
  visibility: "foreground",
  openLauncher: () => {},
  navigateTo: () => {},
  emit: () => {},
  on: () => () => {},
  onOpenWith: () => () => {},
};

const PortalContext = createContext<PortalApi>(standalone);

export function usePortal(): PortalApi {
  return useContext(PortalContext);
}

export function usePortalVisibility(): Visibility {
  return useContext(PortalContext).visibility;
}

type BusHandler = (event: BusEvent) => void;
type OpenWithHandler = (path: string | undefined, payload: unknown) => void;

export interface PortalProviderProps {
  /** This app's id — must match its project-defs directory name. */
  readonly appId: string;
  readonly appVersion?: string;
  readonly children: ReactNode;
}

export function PortalProvider({
  appId,
  appVersion,
  children,
}: PortalProviderProps): ReactNode {
  const [hosted, setHosted] = useState(false);
  const [mode, setMode] = useState<ThemeMode>("light");
  const [catalog, setCatalog] = useState<readonly AppMeta[]>([]);
  const [visibility, setVisibility] = useState<Visibility>("foreground");

  // The portal's origin, learned from `welcome`; until then we don't trust or
  // target any specific origin.
  const portalOrigin = useRef<string | null>(null);
  const busHandlers = useRef(new Map<string, Set<BusHandler>>());
  const openWithHandlers = useRef(new Set<OpenWithHandler>());

  const send = useCallback((msg: Record<string, unknown>) => {
    const target = portalOrigin.current;
    // Pre-handshake `hello` goes to "*" (carries no secrets); everything else
    // is locked to the portal's confirmed origin.
    window.parent.postMessage({ ...envelope, ...msg }, target ?? "*");
  }, []);

  useEffect(() => {
    // Not in a frame → certainly standalone, skip the handshake entirely.
    if (window.parent === window.self) return undefined;

    let settled = false;

    const onMessage = (ev: MessageEvent) => {
      const msg = parse<PortalMessage>(ev.data);
      if (msg === null) return;
      // First contact pins the origin; later messages must match it.
      if (portalOrigin.current === null && msg.kind === "welcome") {
        portalOrigin.current = ev.origin;
      } else if (ev.origin !== portalOrigin.current) {
        return;
      }

      switch (msg.kind) {
        case "welcome":
          settled = true;
          setHosted(true);
          setMode(msg.mode);
          setCatalog(msg.catalog);
          break;
        case "theme":
          setMode(msg.mode);
          break;
        case "visibility":
          setVisibility(msg.state);
          break;
        case "open-with":
          for (const h of openWithHandlers.current) h(msg.path, msg.payload);
          break;
        case "event":
          for (const h of busHandlers.current.get(msg.event.type) ?? []) {
            h(msg.event);
          }
          break;
        default:
          break;
      }
    };

    window.addEventListener("message", onMessage);
    send({ kind: "hello", appId, appVersion });
    const timer = window.setTimeout(() => {
      if (!settled) setHosted(false);
    }, HANDSHAKE_TIMEOUT_MS);

    return () => {
      window.removeEventListener("message", onMessage);
      window.clearTimeout(timer);
    };
  }, [appId, appVersion, send]);

  const api = useMemo<PortalApi>(
    () => ({
      hosted,
      mode,
      catalog,
      visibility,
      openLauncher: () => send({ kind: "open-launcher" }),
      navigateTo: (id, opts) =>
        send({ kind: "navigate", appId: id, path: opts?.path, payload: opts?.payload }),
      emit: (type, payload) => send({ kind: "emit", event: { type, payload } }),
      on: (type, handler) => {
        const set = busHandlers.current.get(type) ?? new Set<BusHandler>();
        set.add(handler);
        busHandlers.current.set(type, set);
        return () => set.delete(handler);
      },
      onOpenWith: (handler) => {
        openWithHandlers.current.add(handler);
        return () => openWithHandlers.current.delete(handler);
      },
    }),
    [hosted, mode, catalog, visibility, send],
  );

  // No chrome is injected here. The app places <PortalLauncherButton/> in its
  // own header where it fits; that button self-hides when not hosted.
  return <PortalContext.Provider value={api}>{children}</PortalContext.Provider>;
}
