// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/settings-sheet.tsx
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// SettingsSheet — the unified settings affordance for the atlantis ecosystem.
//
// A gear button that opens the SAME settings surface everywhere, only the
// container adapts to the viewport:
//
//   • mobile (< sm): a bottom sheet that slides up from the bottom edge.
//   • desktop (≥ sm): a centered dialog.
//
// Apps fill it with their own settings rows via `children` (today: the shared
// ThemeModeControl). Keeping the gear + surface in the SDK means every app's
// settings look and behave identically; to evolve them, edit THIS file and
// re-run `harness shell sync`.

import DarkModeIcon from "@mui/icons-material/DarkMode";
import LightModeIcon from "@mui/icons-material/LightMode";
import SettingsIcon from "@mui/icons-material/Settings";
import SettingsBrightnessIcon from "@mui/icons-material/SettingsBrightness";
import {
  Box,
  Dialog,
  DialogContent,
  DialogTitle,
  Drawer,
  IconButton,
  ToggleButton,
  ToggleButtonGroup,
  Tooltip,
  Typography,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import { type ReactNode, useState } from "react";

export interface SettingsSheetProps {
  /** Heading at the top of the sheet/dialog. Default "Settings". */
  readonly title?: string;
  /** Settings rows — e.g. a {@link ThemeModeControl}. */
  readonly children: ReactNode;
}

/**
 * The gear + responsive settings surface. Drop it into a top-bar `actions`
 * slot (or any chrome); it owns its own open/close state.
 */
export function SettingsSheet({ title = "Settings", children }: SettingsSheetProps): ReactNode {
  const [open, setOpen] = useState(false);
  const theme = useTheme();
  // `sm` (600px): true phones get the bottom sheet; tablets, desktops, and the
  // (typically wide) portal iframe get the centered dialog.
  const isMobile = useMediaQuery(theme.breakpoints.down("sm"));
  const close = (): void => {
    setOpen(false);
  };

  const rows = (
    <Box sx={{ display: "flex", flexDirection: "column", gap: 2 }}>{children}</Box>
  );

  return (
    <>
      <Tooltip title="Settings">
        <IconButton aria-label="settings" onClick={() => setOpen(true)} size="small">
          <SettingsIcon fontSize="small" />
        </IconButton>
      </Tooltip>
      {isMobile ? (
        <Drawer
          anchor="bottom"
          open={open}
          onClose={close}
          slotProps={{
            paper: {
              sx: {
                borderTopLeftRadius: 16,
                borderTopRightRadius: 16,
                px: 2,
                pt: 2,
                pb: "calc(16px + env(safe-area-inset-bottom, 0px))",
              },
            },
          }}
        >
          {/* A grab handle reads as "drag me down to dismiss" on touch. */}
          <Box
            sx={{
              width: 36,
              height: 4,
              borderRadius: 2,
              bgcolor: "divider",
              mx: "auto",
              mb: 1.5,
            }}
          />
          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1.5 }}>
            {title}
          </Typography>
          {rows}
        </Drawer>
      ) : (
        <Dialog open={open} onClose={close} maxWidth="xs" fullWidth>
          <DialogTitle sx={{ fontWeight: 700 }}>{title}</DialogTitle>
          <DialogContent>{rows}</DialogContent>
        </Dialog>
      )}
    </>
  );
}

/** The user's theme preference. "system" follows the OS; resolved to a concrete
 * light/dark `ThemeMode` (see protocol.ts) before it reaches the MUI theme. */
export type ThemeChoice = "system" | "light" | "dark";

const THEME_CHOICES: readonly { value: ThemeChoice; label: string; icon: ReactNode }[] = [
  { value: "system", label: "System", icon: <SettingsBrightnessIcon fontSize="small" /> },
  { value: "light", label: "Light", icon: <LightModeIcon fontSize="small" /> },
  { value: "dark", label: "Dark", icon: <DarkModeIcon fontSize="small" /> },
];

/**
 * Shared theme picker: a System / Light / Dark segmented control. Goes inside a
 * {@link SettingsSheet}. Identical in every app so theme selection feels the
 * same product-wide.
 */
export function ThemeModeControl(props: {
  readonly value: ThemeChoice;
  readonly onChange: (value: ThemeChoice) => void;
}): ReactNode {
  const { value, onChange } = props;
  return (
    <Box>
      <Typography variant="overline" sx={{ color: "text.secondary", display: "block", mb: 0.5 }}>
        Theme
      </Typography>
      <ToggleButtonGroup
        value={value}
        exclusive
        fullWidth
        size="small"
        onChange={(_e, next: ThemeChoice | null) => {
          // null = the active button was re-clicked; keep the current choice.
          if (next !== null) onChange(next);
        }}
      >
        {THEME_CHOICES.map((c) => (
          <ToggleButton key={c.value} value={c.value} sx={{ gap: 0.5, textTransform: "none" }}>
            {c.icon}
            {c.label}
          </ToggleButton>
        ))}
      </ToggleButtonGroup>
    </Box>
  );
}
