// ╔════════════════════════════════════════════════════════════════╗
// ║  CODE GENERATED BY `harness shell sync` — DO NOT EDIT.           ║
// ║  Source of truth: columbus/interface/app-shell/theme.ts
// ║  Edit there, then re-run `harness shell sync` to propagate.      ║
// ╚════════════════════════════════════════════════════════════════╝

// The shared MUI theme. Every hosted app calls `createAtlantisTheme` with its
// own brand `primary` color: the design language (shape, typography, density,
// component overrides) is unified here so all apps look like one product,
// while the accent stays per-app so you always know where you are.
//
// To evolve the unified look, edit THIS file and re-run `harness shell sync` —
// the change propagates to every app's vendored copy.

import { createTheme, type Theme } from "@mui/material/styles";

import type { ThemeMode } from "./protocol";

export interface AtlantisThemeOptions {
  /** App brand accent → palette.primary.main (from project-defs `webui.color`). */
  readonly primary: string;
  readonly mode: ThemeMode;
}

export function createAtlantisTheme({
  primary,
  mode,
}: AtlantisThemeOptions): Theme {
  return createTheme({
    palette: {
      mode,
      primary: { main: primary },
    },
    shape: { borderRadius: 10 },
    typography: {
      fontFamily:
        '"Inter", "IBM Plex Sans", system-ui, -apple-system, "Segoe UI", sans-serif',
      button: { textTransform: "none", fontWeight: 600 },
    },
    components: {
      MuiButton: { defaultProps: { disableElevation: true } },
      MuiPaper: { defaultProps: { variant: "outlined" } },
      MuiAppBar: { defaultProps: { elevation: 0, color: "default" } },
    },
  });
}
